In [1]:
import numpy as np 
import pickle
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('/Users/ankitbista/Desktop/practice/HousePricePrediction/dataset.csv')

In [4]:
df.head(5)

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price,HouseAge
0,1,1360.0,5,4,3,1970,0,0,0,149919.0,55
1,2,4272.0,5,4,3,1958,0,0,0,424998.0,67
2,3,3592.0,2,2,3,1938,0,2,0,266746.0,87
3,4,966.0,4,2,2,1902,2,1,1,244020.0,123
4,5,4926.0,1,4,2,1975,0,1,1,636056.0,50

In [5]:
encoder = LabelEncoder()
df['Location'] = encoder.fit_transform(df['Location'])
df

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price,HouseAge
0,1,1360.0,5,4,3,1970,0,0,0,149919.0,55
1,2,4272.0,5,4,3,1958,0,0,0,424998.0,67
2,3,3592.0,2,2,3,1938,0,2,0,266746.0,87
3,4,966.0,4,2,2,1902,2,1,1,244020.0,123
4,5,4926.0,1,4,2,1975,0,1,1,636056.0,50
...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994.0,5,4,3,1923,2,3,0,295620.0,102
1996,1997,3046.0,5,2,1,2019,2,3,1,580929.0,6
1997,1998,1062.0,5,1,2,1903,1,3,0,476925.0,122
1998,1999,4062.0,3,1,2,1936,3,0,1,161119.0,89
1999,2000,2989.0,5,1,3,1903,2,1,0,482525.0,122

In [6]:
df['Condition'] = encoder.fit_transform(df['Condition'])
df

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price,HouseAge
0,1,1360.0,5,4,3,1970,0,0,0,149919.0,55
1,2,4272.0,5,4,3,1958,0,0,0,424998.0,67
2,3,3592.0,2,2,3,1938,0,2,0,266746.0,87
3,4,966.0,4,2,2,1902,2,1,1,244020.0,123
4,5,4926.0,1,4,2,1975,0,1,1,636056.0,50
...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994.0,5,4,3,1923,2,3,0,295620.0,102
1996,1997,3046.0,5,2,1,2019,2,3,1,580929.0,6
1997,1998,1062.0,5,1,2,1903,1,3,0,476925.0,122
1998,1999,4062.0,3,1,2,1936,3,0,1,161119.0,89
1999,2000,2989.0,5,1,3,1903,2,1,0,482525.0,122

In [7]:
df['Garage'] = encoder.fit_transform(df['Garage'])
df

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price,HouseAge
0,1,1360.0,5,4,3,1970,0,0,0,149919.0,55
1,2,4272.0,5,4,3,1958,0,0,0,424998.0,67
2,3,3592.0,2,2,3,1938,0,2,0,266746.0,87
3,4,966.0,4,2,2,1902,2,1,1,244020.0,123
4,5,4926.0,1,4,2,1975,0,1,1,636056.0,50
...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994.0,5,4,3,1923,2,3,0,295620.0,102
1996,1997,3046.0,5,2,1,2019,2,3,1,580929.0,6
1997,1998,1062.0,5,1,2,1903,1,3,0,476925.0,122
1998,1999,4062.0,3,1,2,1936,3,0,1,161119.0,89
1999,2000,2989.0,5,1,3,1903,2,1,0,482525.0,122

In [8]:
df.to_csv('/Users/ankitbista/Desktop/practice/HousePricePrediction/dataset.csv',index= False)

In [9]:
# Fit the encoders on your training data
encoder_location = LabelEncoder()
encoder_condition = LabelEncoder()
encoder_garage = LabelEncoder()

# Assuming 'df' is your training data and columns are categorical
encoder_location.fit(df['Location'])
encoder_condition.fit(df['Condition'])
encoder_garage.fit(df['Garage'])

# Save the encoders
with open('encoder_location.pkl', 'wb') as f:
    pickle.dump(encoder_location, f)

with open('encoder_condition.pkl', 'wb') as f:
    pickle.dump(encoder_condition, f)

with open('encoder_garage.pkl', 'wb') as f:
    pickle.dump(encoder_garage, f)